version: '3'
services: 
    add-user:
       image: add-user:1.0
       ports:
            - 3000:3000
       depends_on:
            - mongodb-test
    mongodb-test:                # container name (--name param)
        image: mongo            # the image tag
        ports:
            - 27018:27017 
        environment:
            - MONGO_INITDB_DATABASE=JamesTestDB
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=123
        volumes:
            - mongo-data:/data/db   # position to save db data within the container
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8080:8081
        depends_on:
            - mongodb-test          # wait for the container mongodb to start
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=123
            - ME_CONFIG_MONGODB_SERVER=mongodb-test 
volumes:
    mongo-data:                     # volume name
        driver: local